"""phase2 ingestion fields

Revision ID: 8f008b42145c
Revises: 8399dceac96e
Create Date: 2025-12-23 10:43:34.266235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f008b42145c'
down_revision: Union[str, Sequence[str], None] = '8399dceac96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelf_items', sa.Column('isbn13', sa.String(length=13), nullable=True))
    op.add_column('shelf_items', sa.Column('isbn10', sa.String(length=10), nullable=True))
    op.add_column('shelf_items', sa.Column('asin', sa.String(length=20), nullable=True))
    op.add_column('shelf_items', sa.Column('goodreads_book_id', sa.String(length=40), nullable=True))
    op.add_column('shelf_items', sa.Column('normalized_title', sa.String(length=600), nullable=False))
    op.add_column('shelf_items', sa.Column('normalized_author', sa.String(length=400), nullable=False))
    op.add_column('shelf_items', sa.Column('normalized_key', sa.String(length=1100), nullable=False))
    op.add_column('shelf_items', sa.Column('needs_fuzzy_match', sa.Boolean(), nullable=False))
    op.add_column('shelf_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_shelf_items_user_title_author'), table_name='shelf_items')
    op.create_index('ix_shelf_items_user_normkey', 'shelf_items', ['user_id', 'normalized_key'], unique=False)
    op.create_unique_constraint('uq_shelf_item_user_normkey', 'shelf_items', ['user_id', 'normalized_key'])
    op.add_column('shelf_sources', sa.Column('shelf_name', sa.String(length=200), nullable=True))
    op.add_column('shelf_sources', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('shelf_sources', sa.Column('last_imported_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_shelf_source_user_type_ref', 'shelf_sources', ['user_id', 'source_type', 'source_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shelf_source_user_type_ref', 'shelf_sources', type_='unique')
    op.drop_column('shelf_sources', 'last_imported_at')
    op.drop_column('shelf_sources', 'is_active')
    op.drop_column('shelf_sources', 'shelf_name')
    op.drop_constraint('uq_shelf_item_user_normkey', 'shelf_items', type_='unique')
    op.drop_index('ix_shelf_items_user_normkey', table_name='shelf_items')
    op.create_index(op.f('ix_shelf_items_user_title_author'), 'shelf_items', ['user_id', 'title', 'author'], unique=False)
    op.drop_column('shelf_items', 'updated_at')
    op.drop_column('shelf_items', 'needs_fuzzy_match')
    op.drop_column('shelf_items', 'normalized_key')
    op.drop_column('shelf_items', 'normalized_author')
    op.drop_column('shelf_items', 'normalized_title')
    op.drop_column('shelf_items', 'goodreads_book_id')
    op.drop_column('shelf_items', 'asin')
    op.drop_column('shelf_items', 'isbn10')
    op.drop_column('shelf_items', 'isbn13')
    # ### end Alembic commands ###
