"""phase2 ingestion fields

Revision ID: 8f008b42145c
Revises: 8399dceac96e
Create Date: 2025-12-23 10:43:34.266235

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f008b42145c"
down_revision: Union[str, Sequence[str], None] = "8399dceac96e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shelf_items") as batch_op:
        batch_op.add_column(sa.Column("isbn13", sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column("isbn10", sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column("asin", sa.String(length=20), nullable=True))
        batch_op.add_column(
            sa.Column("goodreads_book_id", sa.String(length=40), nullable=True)
        )
        batch_op.add_column(
            sa.Column("normalized_title", sa.String(length=600), nullable=False)
        )
        batch_op.add_column(
            sa.Column("normalized_author", sa.String(length=400), nullable=False)
        )
        batch_op.add_column(
            sa.Column("normalized_key", sa.String(length=1100), nullable=False)
        )
        batch_op.add_column(
            sa.Column("needs_fuzzy_match", sa.Boolean(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
        )
        batch_op.drop_index(op.f("ix_shelf_items_user_title_author"))
        batch_op.create_index(
            "ix_shelf_items_user_normkey",
            ["user_id", "normalized_key"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "uq_shelf_item_user_normkey", ["user_id", "normalized_key"]
        )

    with op.batch_alter_table("shelf_sources") as batch_op:
        batch_op.add_column(
            sa.Column("shelf_name", sa.String(length=200), nullable=True)
        )
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("last_imported_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.create_unique_constraint(
            "uq_shelf_source_user_type_ref",
            ["user_id", "source_type", "source_ref"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shelf_sources") as batch_op:
        batch_op.drop_constraint("uq_shelf_source_user_type_ref", type_="unique")
        batch_op.drop_column("last_imported_at")
        batch_op.drop_column("is_active")
        batch_op.drop_column("shelf_name")

    with op.batch_alter_table("shelf_items") as batch_op:
        batch_op.drop_constraint("uq_shelf_item_user_normkey", type_="unique")
        batch_op.drop_index("ix_shelf_items_user_normkey")
        batch_op.create_index(
            op.f("ix_shelf_items_user_title_author"),
            ["user_id", "title", "author"],
            unique=False,
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("needs_fuzzy_match")
        batch_op.drop_column("normalized_key")
        batch_op.drop_column("normalized_author")
        batch_op.drop_column("normalized_title")
        batch_op.drop_column("goodreads_book_id")
        batch_op.drop_column("asin")
        batch_op.drop_column("isbn10")
        batch_op.drop_column("isbn13")
    # ### end Alembic commands ###
