"""phase3 catalog matching

Revision ID: b2c2190162bb
Revises: c7a5b2b4af1e
Create Date: 2025-12-23 19:37:31.748233

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b2c2190162bb"
down_revision: Union[str, Sequence[str], None] = "c7a5b2b4af1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_item_id", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("author", sa.String(length=240), nullable=True),
        sa.Column("isbn10", sa.String(length=10), nullable=True),
        sa.Column("isbn13", sa.String(length=13), nullable=True),
        sa.Column("asin", sa.String(length=20), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_item_id", name="uq_catalog_items_provider_item"
        ),
    )
    op.create_table(
        "availability_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("catalog_item_id", sa.String(length=36), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("copies_available", sa.Integer(), nullable=True),
        sa.Column("copies_total", sa.Integer(), nullable=True),
        sa.Column("holds", sa.Integer(), nullable=True),
        sa.Column("deep_link", sa.String(length=500), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_item_id"], ["catalog_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "catalog_item_id", "format", name="uq_avail_user_item_format"
        ),
    )
    op.create_index(
        op.f("ix_availability_snapshots_catalog_item_id"),
        "availability_snapshots",
        ["catalog_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_availability_snapshots_user_id"),
        "availability_snapshots",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "catalog_matches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("shelf_item_id", sa.String(length=36), nullable=False),
        sa.Column("catalog_item_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_item_id"], ["catalog_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["shelf_item_id"], ["shelf_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "shelf_item_id", name="uq_catalog_match_user_shelf_item"
        ),
    )
    op.create_index(
        op.f("ix_catalog_matches_catalog_item_id"),
        "catalog_matches",
        ["catalog_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_matches_shelf_item_id"),
        "catalog_matches",
        ["shelf_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_matches_user_id"), "catalog_matches", ["user_id"], unique=False
    )
    op.alter_column(
        "shelf_items",
        "isbn10",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "shelf_items",
        "isbn13",
        existing_type=sa.VARCHAR(length=13),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_shelf_items_user_normkey"), table_name="shelf_items")
    op.drop_constraint(
        op.f("uq_shelf_item_user_normkey"), "shelf_items", type_="unique"
    )
    op.create_index(
        "ix_shelf_items_source_external_unique",
        "shelf_items",
        ["shelf_source_id", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_column("shelf_items", "normalized_key")
    op.drop_column("shelf_items", "goodreads_book_id")
    op.drop_constraint(
        op.f("uq_shelf_source_user_type_ref"), "shelf_sources", type_="unique"
    )
    op.drop_column("shelf_sources", "shelf_name")
    op.drop_column("shelf_sources", "last_imported_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shelf_sources",
        sa.Column(
            "last_imported_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "shelf_sources",
        sa.Column(
            "shelf_name", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
    )
    op.create_unique_constraint(
        op.f("uq_shelf_source_user_type_ref"),
        "shelf_sources",
        ["user_id", "source_type", "source_ref"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "shelf_items",
        sa.Column(
            "goodreads_book_id",
            sa.VARCHAR(length=40),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "shelf_items",
        sa.Column(
            "normalized_key",
            sa.VARCHAR(length=1100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(
        "ix_shelf_items_source_external_unique",
        table_name="shelf_items",
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_shelf_item_user_normkey"),
        "shelf_items",
        ["user_id", "normalized_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_shelf_items_user_normkey"),
        "shelf_items",
        ["user_id", "normalized_key"],
        unique=False,
    )
    op.alter_column(
        "shelf_items",
        "isbn13",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=13),
        existing_nullable=True,
    )
    op.alter_column(
        "shelf_items",
        "isbn10",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_catalog_matches_user_id"), table_name="catalog_matches")
    op.drop_index(
        op.f("ix_catalog_matches_shelf_item_id"), table_name="catalog_matches"
    )
    op.drop_index(
        op.f("ix_catalog_matches_catalog_item_id"), table_name="catalog_matches"
    )
    op.drop_table("catalog_matches")
    op.drop_index(
        op.f("ix_availability_snapshots_user_id"), table_name="availability_snapshots"
    )
    op.drop_index(
        op.f("ix_availability_snapshots_catalog_item_id"),
        table_name="availability_snapshots",
    )
    op.drop_table("availability_snapshots")
    op.drop_table("catalog_items")
    # ### end Alembic commands ###
