"""phase3 catalog matching

Revision ID: bedca43b8c03
Revises: b2c2190162bb
Create Date: 2025-12-23 19:50:47.846892

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bedca43b8c03"
down_revision: Union[str, Sequence[str], None] = "b2c2190162bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
